---
# Pipeline will only trigger when something is pushed to main branch 
workflow:  
    rules:
      - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
        when: never
      - when: always
    

variables:
  TF_VERSION: 1.4.1

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/

  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py --user
  - python3 -m pip install --user ansible
  - apt-get update && apt-get install -y unzip
  - terraform --version
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519
  - ls -la ~/.ssh

stages:
  - apply

terraform_apply:
  stage: apply
  script:
    - terraform init
    - terraform validate
    - terraform plan -var-file=terraform.tfvars -out=tfplan
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - tfplan
    