variables:
  TF_VERSION: 1.3.9
  DO_SSH_KEY: case
before_script:
  - apt-get update && apt-get install -y unzip
  - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)

  - ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519
  - ls -la ~/.ssh

stages:
  - plan
  - apply
  - destroy

terraform:
  stage: plan_apply
  script:
    - terraform init
    - terraform validate
    - terraform plan -var-file=terraform.tfvars -out=tfplan
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - tfplan
  environment:
    name: production
    on_stop: stop_terraform

stop_terraform:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  allow_failure: true
  environment:
    name: production
    action: stop