variables:
  TF_VERSION: 0.14.9

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
  
stages:
  - plan
  - apply
  - destroy

terraform:
  stage: plan
  script:
    - terraform init
    - terraform validate
    - terraform plan -var-file=terraform.tfvars -out=tfplan
  artifacts:
    paths:
      - tfplan

terraform_apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  environment:
    name: production

    on_stop: stop_terraform

stop_terraform:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  allow_failure: true
  environment:
    name: production
    action: stop