#cloud-config

package_update: true
package_upgrade: true
groups:
  - docker

system_info:
  default_user:
    groups: [ docker ]

packages:
  - nginx
  - nftables
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
  - git 
  - vim 
  - hugo
runcmd:
  - systemctl enable nftables.service
  - systemctl start nftables.service
  - echo "#!/usr/sbin/nft -f" > /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "flush ruleset" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "table inet filter {" >> /etc/nftables.conf
  - echo "  chain input {" >> /etc/nftables.conf
  - echo "    type filter hook input priority 0;" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    iifname \"lo\" accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    ct state established,related accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    tcp dport 22 accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    tcp dport 80 accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    tcp dport 443 accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    tcp dport {2376,2377,7946} accept" >> /etc/nftables.conf
  - echo "    udp dport {7946,4789} accept" >> /etc/nftables.conf
  - echo "" >> /etc/nftables.conf
  - echo "    drop" >> /etc/nftables.conf
  - echo "  }" >> /etc/nftables.conf
  - echo "}" >> /etc/nftables.conf
  - systemctl restart nftables.service
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable docker.service
  - systemctl start docker.service
  
final_message: "The system is finally up, after $UPTIME seconds"
