---
- name: Install Nginx and configure nftables for web server
  hosts: all
  become: true
  
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Configure nftables for web server
      apt:
        name: nftables
        state: present
      notify:
        - enable nftables

  handlers:
    - name: enable nftables
      service:
        name: nftables
        enabled: true
        state: started

    - name: configure nftables
      become: true
      template:
        src: nftables.conf.j2
        dest: /etc/nftables.conf
        mode: '0644'
      notify:
        - restart nftables

  post_tasks:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

  handlers:
    - name: restart nftables
      service:
        name: nftables
        state: restarted
